# Generated by Django 4.0.1 on 2022-02-24 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('acc_type', models.CharField(choices=[('personal', 'Personal'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=60)),
                ('initial_amount', models.FloatField(default=0.0, max_length=15)),
                ('rem_amount', models.FloatField(default=0.0)),
                ('status', models.IntegerField(default=0)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('user_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('address', models.TextField()),
                ('p_number', models.CharField(max_length=10)),
                ('date_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrackMoneyTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField()),
                ('rem_amount', models.FloatField()),
                ('total_amount', models.FloatField(default=0.0)),
                ('extra_note', models.TextField()),
                ('date_time', models.DateField(default=django.utils.timezone.now)),
                ('trackmoney_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexpense.trackmoney')),
            ],
        ),
        migrations.AddField(
            model_name='trackmoney',
            name='tx_acc',
            field=models.ManyToManyField(to='myexpense.TrackMoneyTx'),
        ),
        migrations.AddField(
            model_name='trackmoney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('amount', models.FloatField()),
                ('date_time', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='0', max_length=50)),
                ('m_number', models.CharField(max_length=10)),
                ('cat_type', models.CharField(choices=[('0', 'Borrow Money'), ('1', 'Lent Money')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('hospital', 'Hospital'), ('other_income', 'Other Income'), ('pension', 'Pension'), ('gift', 'Gift'), ('travel', 'Travel'), ('refund', 'Refund'), ('grocery', 'Grocery'), ('restourant', 'Restourant'), ('supermarket', 'Supermarket'), ('bus', 'Bus'), ('car', 'Car'), ('metro', 'Metro'), ('health', 'Health'), ('toll', 'Toll'), ('house', 'House'), ('train', 'Train'), ('airplane', 'Airplane'), ('visits', 'Visits'), ('fuel', 'Fuel'), ('gas', 'Gas'), ('repair', 'Repair'), ('maintanance', 'Maintanance'), ('parking', 'Parking'), ('fines', 'Fines'), ('loan_mortages', 'Loan/Mortages'), ('hotel', 'Hotel'), ('rent', 'Rent'), ('tv', 'TV'), ('furniture', 'Furniture'), ('decoration', 'Decoration'), ('water', 'Water'), ('books', 'Books'), ('phone', 'Phone'), ('doctor', 'Docter'), ('travel', 'Travel'), ('garden', 'Garden'), ('movies', 'Movies'), ('clothing', 'Clothing'), ('dalan', 'dalan'), ('market', 'Market')], max_length=100)),
                ('date_time', models.DateField(default=django.utils.timezone.now)),
                ('add_spend', models.IntegerField(choices=[(0, 'Spend'), (1, 'Add')])),
                ('extra_note', models.TextField()),
                ('exp_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myexpense.expaccounts')),
            ],
        ),
    ]
