# Generated by Django 4.0.1 on 2022-02-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexpense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exptransactions',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('hospital', 'Hospital'), ('other_income', 'Other Income'), ('pension', 'Pension'), ('gift', 'Gift'), ('travel', 'Travel'), ('refund', 'Refund'), ('grocery', 'Grocery'), ('restourant', 'Restourant'), ('supermarket', 'Supermarket'), ('bus', 'Bus'), ('car', 'Car'), ('metro', 'Metro'), ('health', 'Health'), ('toll', 'Toll'), ('house', 'House'), ('train', 'Train'), ('airplane', 'Airplane'), ('visits', 'Visits'), ('fuel', 'Fuel'), ('gas', 'Gas'), ('repair', 'Repair'), ('maintanance', 'Maintanance'), ('parking', 'Parking'), ('fines', 'Fines'), ('loan_mortages', 'Loan/Mortages'), ('hotel', 'Hotel'), ('rent', 'Rent'), ('tv', 'TV'), ('furniture', 'Furniture'), ('decoration', 'Decoration'), ('water', 'Water'), ('books', 'Books'), ('phone', 'Phone'), ('doctor', 'Docter'), ('travel', 'Travel'), ('garden', 'Garden'), ('movies', 'Movies'), ('clothing', 'Clothing'), ('dalan', 'dalan'), ('market', 'Market'), ('other', 'Other')], max_length=100),
        ),
    ]
